// Explicit read-only data contract. Never expose whole schemas or documents to a model.
const common = { _id: 'id', createdAt: 'date' };
function dataset(model, permission, title, path, fields, note = '') {
  return { model, permission, title, path, fields: { ...common, ...fields }, note };
}

export const DATASETS = {
  products: dataset('Product', 'products.view', 'محصولات', '/p-admin/admin-products', {
    name: 'text', sku: 'text', slug: 'text', basePrice: 'number', isActive: 'boolean',
    brand: 'id', category: 'id', sport: 'id',
  }, 'basePrice is base Toman, not final sale price. No inventory field. Creator is in activity tool.'),
  orders: dataset('Order', 'orders.view', 'سفارش‌ها', '/p-admin/admin-orders', {
    trackingCode: 'text', user: 'id', totalPrice: 'number', paymentStatus: 'text',
    fulfillmentStatus: 'text', paymentMethod: 'text',
  }, 'Toman. paymentStatus UNPAID/PARTIALLY_PAID/PAID; fulfillmentStatus WAITING/NEEDS_PURCHASE/PROCESSING/SENT/DELIVERED/CANCELED. Revenue/collected/outstanding: use finance.'),
  users: dataset('User', 'users.view', 'کاربران', '/p-admin/users', {
    name: 'text', lastName: 'text', role: 'text', isBanned: 'boolean',
  }),
  payments: dataset('Payment', 'payments.view', 'پرداخت‌ها', '/p-admin/admin-orders', {
    order: 'id', amount: 'number', status: 'text', method: 'text',
  }, 'Toman. status PENDING/PAID/FAILED/REJECTED. Sum of PAID payments is not total store revenue.'),
  installments: dataset('Installment', 'installments.view', 'اقساط', '/p-admin/financial/installments', {
    order: 'id', totalAmount: 'number', downPayment: 'number', numberOfChecks: 'number', status: 'text',
  }, 'Toman; PENDING/ACTIVE/COMPLETED/DEFAULTED. Does not expose individual check due dates.'),
  tickets: dataset('Ticket', 'tickets.view', 'تیکت‌ها', '/p-admin/support?tab=tickets', {
    subject: 'text', user: 'id', status: 'text', priority: 'text', department: 'text',
  }, 'status open/answered/pending_user/closed; priority low/medium/high/urgent. Subject only, no message bodies.'),
  articles: dataset('Article', 'articles.view', 'مقاله‌ها', '/p-admin/admin-articles', {
    title: 'text', slug: 'text', status: 'text', author: 'id', publishedAt: 'date',
  }, 'draft/review/scheduled/published/archived; excludes deleted articles.'),
  usedProducts: dataset('UsedProduct', 'secondHand.view', 'محصولات دست دوم', '/p-admin/admin-secondHands/used-products', {
    name: 'text', slug: 'text', price: 'number', status: 'text', overallScore: 'number',
  }, 'Toman; available/reserved/sold.'),
  brands: dataset('Brand', 'brands.view', 'برندها', '/p-admin/admin-brands', { name: 'text', title: 'text', slug: 'text' }),
  sports: dataset('Sport', 'sports.view', 'ورزش‌ها', '/p-admin/admin-sports', { name: 'text', title: 'text', slug: 'text' }),
  categories: dataset('Category', 'categories.view', 'دسته‌بندی‌ها', '/p-admin/admin-categories', { name: 'text', title: 'text', slug: 'text', sport: 'id' }),
};

export const TOOL_PERMISSIONS = { activity: 'admins.viewActivity', finance: 'analytics.view' };
export const LIMITS = { message: 1500, history: 6, historyChars: 4500, queries: 3, filters: 6, rows: 8, rounds: 2, bodyBytes: 24000, evidenceChars: 16000 };
export const hasOwn = (object, key) => typeof key === 'string' && Object.hasOwn(object, key);

export function availableCatalog(permissions) {
  const allowed = new Set(permissions);
  return Object.entries(DATASETS).filter(([, d]) => allowed.has(d.permission)).map(([name, d]) => ({
    name, title: d.title, fields: d.fields, note: d.note,
  }));
}

// Actual route URLs are generated by the server, never by the language model.
export function recordPath(datasetName, row) {
  const id = String(row._id || '');
  if (!/^[a-f\d]{24}$/i.test(id)) return DATASETS[datasetName]?.path;
  if (datasetName === 'orders') return `/p-admin/admin-orders/${id}`;
  if (datasetName === 'users') return `/p-admin/users/${id}`;
  if (datasetName === 'tickets') return `/p-admin/support/tickets/${id}`;
  if (datasetName === 'installments') return `/p-admin/financial/installments/${id}`;
  if (datasetName === 'articles') return `/p-admin/admin-articles/${id}/preview`;
  // Product details live in an editor, so permission checking may fall back to the list.
  if (datasetName === 'products') return `/p-admin/admin-products/edit/${id}`;
  return DATASETS[datasetName]?.path;
}
